/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogBlock: typeof import('./src/components/blogs/blogBlock.vue')['default']
    BlogLink: typeof import('./src/components/blogs/blogLink.vue')['default']
    End: typeof import('./src/components/end.vue')['default']
    IconLink: typeof import('./src/components/iconLink.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    MyHeader: typeof import('./src/components/myHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VPs: typeof import('./src/components/vPs.vue')['default']
  }
}
